export const productTypes = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',
  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
  PRODUCT_DETAILS_FAILURE: 'PRODUCT_DETAILS_FAILURE',
};

export const cartTypes = {
  GET_CART_ITEM_REQUEST: 'GET_CART_ITEM_REQUEST',
  GET_CART_ITEM_SUCCESS: 'GET_CART_ITEM_SUCCESS',
  GET_CART_ITEM_FAILURE: 'GET_CART_ITEM_FAILURE',
  CART_ADD_ITEM_REQUEST: 'CART_ADD_ITEM_REQUEST',
  CART_ADD_ITEM_SUCCESS: 'CART_ADD_ITEM_SUCCESS',
  CART_ADD_ITEM_FAILURE: 'CART_ADD_ITEM_FAILURE',
  CART_REMOVE_ITEM_REQUEST: 'CART_REMOVE_ITEM_REQUEST',
  CART_REMOVE_ITEM_SUCCESS: 'CART_REMOVE_ITEM_SUCCESS',
  CART_REMOVE_ITEM_FAILURE: 'CART_REMOVE_ITEM_FAILURE',
};
