export const productTypes = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
  PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',
  PRODUCT_DETAILS_REQUEST: 'PRODUCT_DETAILS_REQUEST',
  PRODUCT_DETAILS_SUCCESS: 'PRODUCT_DETAILS_SUCCESS',
  PRODUCT_DETAILS_FAILURE: 'PRODUCT_DETAILS_FAILURE',
};

export const cartTypes = {
  GET_CART_ITEM_REQUEST: 'GET_CART_ITEM_REQUEST',
  GET_CART_ITEM_SUCCESS: 'GET_CART_ITEM_SUCCESS',
  GET_CART_ITEM_FAILURE: 'GET_CART_ITEM_FAILURE',
  CART_ADD_ITEM_REQUEST: 'CART_ADD_ITEM_REQUEST',
  CART_ADD_ITEM_SUCCESS: 'CART_ADD_ITEM_SUCCESS',
  CART_ADD_ITEM_FAILURE: 'CART_ADD_ITEM_FAILURE',
  CART_REMOVE_ITEM_REQUEST: 'CART_REMOVE_ITEM_REQUEST',
  CART_REMOVE_ITEM_SUCCESS: 'CART_REMOVE_ITEM_SUCCESS',
  CART_REMOVE_ITEM_FAILURE: 'CART_REMOVE_ITEM_FAILURE',
  CART_SHIPPING_ADDRESS: 'CART_SHIPPING_ADDRESS',
  CART_PAYMENT_METHOD: 'CART_PAYMENT_METHOD',
};

export const userTypes = {
  USER_SIGNIN_REQUEST: 'USER_SIGNIN_REQUEST',
  USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
  USER_SIGNIN_FAILURE: 'USER_SIGNIN_FAILURE',
  USER_SIGNOUT: 'USER_SIGNOUT',
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
};
